title: paradise-gl
description: "Computer Graphics Final Project - Paradise: Forest and Water Simulation."
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
